### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [JBirdVegas/external_jbirdvegas_mGerrit#40]
There's a thread for its inclusion at: https://f-droid.org/forums/topic/mgerrit/

**Comment by JBirdVegas** [comment]
Your welcome to submit a pull request.  I have no objection to `F-Droid`'s inclusion

**Comment by pizzamaker** [comment]
Adding packages to F-Droid is generally done by sending a pull request at https://gitlab.com/fdroid/fdroiddata

You need to install f-droid server and data locally, create a metadata file like one of these https://gitlab.com/fdroid/fdroiddata/tree/master/metadata and see if your local f-droid server can build mGerrit. If it does, you commit your changes and send a pull request.

**Comment by M2ck** [comment]
Already available [here](https://f-droid.org/repository/browse/?fdfilter=mgerrit&fdid=com.jbirdvegas.mgerrit) with a mention "Usage of GA has been removed from this build."
PR #39 is not related with its inclusion?

**Comment by pizzamaker** [comment]
Oh you're right! It's been added. Thanks, closing this issue.

**Comment by JBirdVegas** [comment]
Thanks @M2ck... I'm glad they removed the GA so it doesn't conflict with the GP stats, but it would be nice to know how many are downloading from F-Droid out of curiosity.

Looking at the diff from the metadata I like some of the gradle changes.  May pull them into the main stream.  Also might look at adding a `productFlavor` that doesn't include GA tracking if that's something people want.
