### ISSUE TITLE
[Question] Update translation

### ISSUE THREAD

**Issue by M2ck** [JBirdVegas/external_jbirdvegas_mGerrit#43]
Since the AOKP project is unmaintained on Crowdin, how update translation for this app?

Do you plan to open your own translation project or you prefer via a pull request?

**Comment by JBirdVegas** [comment]
Personally I'd prefer pull requests but Crowdin seems to get more translations submitted.  @p4r4n01d I'd like to hear your preference

**Comment by p4r4n01d** [comment]
Yeah same. I would prefer PRs but we haven't got one yet for translations
(but a while anyway). Crowdin would take a bit if extra maintenance (esp.
if we go back to AOKP project), but if that's the only way too get
contributors it well be worth it.

**Comment by M2ck** [comment]
Ok well I will send a PR for update french translation asap.
Thanks!

**Comment by JBirdVegas** [comment]
@M2ck , No sir thank you!
