### ISSUE TITLE
IllegalStateException - Cannot add header view to list -- setAdapter has already been called

### ISSUE THREAD

**Issue by fracz** [JBirdVegas/external_jbirdvegas_mGerrit#47]
I was browsing the source code on my custom Gerrit repository and then after I wanted to exit from source code browser back to the change details screen, application has crashed with the exception mentioned in the title.

Then, when I was trying to start the application again - it was crashing immediately with the same exception. I managed to start the app again only after I had cleaned its data (through the app manager).

I will post more details if I can reproduce it.

[Stack trace](https://photos.google.com/share/AF1QipNBS84yX_YrMBJggpf8Kf_PaQA7q2S6-o13nXRXmkvOULcUlqktxPW7Yw_l94lojQ?key=M0pvMHhISXpiT2JxdUZWSjFvUGdROEFERVNyNEVn):

![](https://lh3.googleusercontent.com/eXw6dRWkTbCTn-tefD4BS28okxvg0kabQo3VR1qlFj7GJh7h_1KSXi-QPbEiGUNoc7eN4SzmEqLhJLTAShiRLr2WYhkWBDHNmsQcqR5znhWzVhslSNDvu931iKHQ8nbDst8VLq4rcjVvwrDNmJtLgQfBZaVklAwWnRKvdIVkPNirEKJdQMf_vkcKB22GoTfkpEOtzMrDNf5iDAwNYeyXOX6qXUsAGT7MUWi0znZEW5nypGjivSVo-PyR4dTIXw6AtlbRdC-p_yCd8-6fr-jAzCxgi3CQLFvn0zRCoHuZEuH2w9VlWWP6M9vu5E1b5ob1hw8aOktB28GF7rTUOJURDecJvYdGz8lPY7EWfOWvgP_N9aqd78DonMN5rMJiS5anmS1wDdpIoEpFPnFzL0Bx-dyR9YlYNvhu1mgSRFOvKl9jblfR9W3t-43KqU2FiqvCAz-SPXs4DbCr2UyciPGDRtG8j4jf5OlGEEPKwokAevRs_EyEs-28tr1QqtzaLLtis6j42VL3qozt46G88ZAUHyoX4YmInhWSvpi3vs9SZgFb-IvG_fZXyPIdbAWsg4FHXBkO=w480-h800-no)

**Comment by p4r4n01d** [comment]
Hi

Thanks for raising this. Can you replicate this issue on a public Gerrit
such as one if the supported ones? If so, can you please provide the Gerrit
URL and what you did to replicate the issue? This will help us fix this
issue sooner.
Also, what version of Android are you running? I have read that this may
not be an issue on some versions of Android.

**Comment by fracz** [comment]
MGerrit 2.111.76, Android 4.1.2. I could not reprocude it so far.
