### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by M2ck** [JBirdVegas/external_jbirdvegas_mGerrit#54]
For match with Material Design guidelines, I suggest to move all options from action bar, except Search feature, into the navigation drawer.
See screenshots below for see what I expect.
By the way, maybe it's not your priority but I've found this tool ([[Tool] Android Material Icon Generator](http://forum.xda-developers.com/tools/programming/tool-android-material-icon-generator-t3333159)) to quickly create a Material icon launcher, it's free and open source!

Action bar
![screenshot_2016-03-16-22-23-03](https://cloud.githubusercontent.com/assets/6850125/14046320/0765985c-f2a1-11e5-87cc-3b27c69b637a.png)
Navigation drawer
![screenshot_2016-03-16-22-23-11](https://cloud.githubusercontent.com/assets/6850125/14046322/0e6c605e-f2a1-11e5-98c1-8790ea5f040d.png)

**Comment by JBirdVegas** [comment]
Looks good.  Another design change I was contemplating was moving the navigation {Review | Merged | Abandoned} to the new bottom navigation style. https://www.google.com/design/spec/components/bottom-navigation.html#

**Comment by M2ck** [comment]
Indeed now that the bottom bar is officially a Material Design's component, it would be nice to play with it!

**Comment by p4r4n01d** [comment]
I am happy moving the Gerrit Switcher into the navigation bar and that is something I can do really quickly. Your screenshot doesn't specify where the Gerrit quick-switch options should go (if you have previously viewed data for another Gerrit instance it will appear after the projects list as AICP does in the following screenshot. I am not sure how settings would fit into this. Either:

a) Have settings separated on its own above the Gerrit quick-switch options. This would look odd IMO
b) Have settings stuck to the bottom (a bit like the navigation drawer on ES File Explorer).
c) Settings option at the bottom of the list but not stuck to the bottom. Ruling this out as the quick-switch options are dynamic.

![content---com google android apps gsa velvet extradex extradexhostprovider-assist com google android apps gsa assist screenshotprovider-com google android apps gsa assist screenshotprovider-screenassistscreenshots-screenshot_201603](https://cloud.githubusercontent.com/assets/5186264/14058292/bf2df906-f36f-11e5-8205-eac13c610a82.png)

Also refresh and help are other options in the menu, where should these go. Refresh doesn't really belong in the navigation bar. I don't think help really does either as it opens a dialog.
![content---com google android apps gsa velvet extradex extradexhostprovider-assist com google android apps gsa assist screenshotprovider-com google android apps gsa assist screenshotprovider-screenassistscreenshots-screenshot_20 1](https://cloud.githubusercontent.com/assets/5186264/14058291/bf2a18c2-f36f-11e5-8215-aa45830dcf85.png)

Sorry but I am going to veto any attempts to move the change status filters from tabs to a bottom navigation bar. Even though it is officially specified in the design guidelines I still believe it looks ugly. Also note that these aren't normally used in combination with a viewpager (tab swiping).

I am prepared to go back to tabs fixed to the toolbar and do some scrolling trickery with them such as what is described here: https://medium.com/@dan1ve/android-howto-material-design-tabs-scrolling-like-in-google-play-music-12273ce07bc with the google play music app

**Comment by M2ck** [comment]
About Projet list and previous Gerrit instance viewed, what do you think to use an arrow which is expanded/reduced when you press it like in Solid Explorer, screenshot below:

![unnamed](https://cloud.githubusercontent.com/assets/6850125/14059563/3b83b804-f345-11e5-9a2a-177f73f668a1.png)

Help button could be under Settings button and for refresh I'm not sure of its utility because swipe-to-refresh feature is already implemented so I think that this button is redundant and useless.

**Comment by p4r4n01d** [comment]
The refresh option and swipe-to-refresh do different things. The refresh option loads data for all three tabs at once and is a workaround for the server version not updating.

**Comment by M2ck** [comment]
My bad I didn't know it!
